name: reviewit
description: "감상을 나누는 SNS형 영화·책 후기 앱"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리: Riverpod
  flutter_riverpod: ^3.0.3

  # 라우팅
  go_router: ^17.0.0

  # HTTP, API
  dio: ^5.9.0

  # JSON 직렬화, 모델링
  freezed_annotation: ^2.4.4
  json_annotation: ^4.8.1

  # 로컬 저장소
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.4

  # 유틸리티
  intl: ^0.20.2
  equatable: ^2.0.7

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # JSON 직렬화, 코드 생성
  build_runner: ^2.4.9
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

flutter:

  uses-material-design: true

